Add Database
Emma-MacK/Software_assessment pull request #41
Opened 2024-01-22 15:23 UTC by aoprince

- Adds database
- Parses json

2024-01-22 17:51 UTC, EKPayne commented
Got a module not fount error when trying to run. requirements.txt 
Module needs updating with module==version

2024-01-23 10:19 UTC, Emma-MacK commented on panel.db.2.py
> +    main_select = Column("main_select", Boolean)
Could we change "main" to mane throughout, since mane is the abbreviation used for "Matched Annotation from NCBI and EMBL-EBI"

2024-01-23 13:58 UTC, EKPayne requested changes
Thanks for sending me the template json file you've been working with. 

I've reviewed the pull request and recommend the following changes before we pull into the develop branch.

2024-01-23 13:58 UTC, EKPayne commented on panel.db.2.py
> +from sqlalchemy.orm import Session
replace Session with sessionmaker

2024-01-23 13:58 UTC, EKPayne commented on panel.db.2.py
> +
Not sure if we shouldn't record a separate ID for each entry. Similar to the way be have genes_table_id

2024-01-23 13:58 UTC, EKPayne commented on panel.db.2.py
> +    genes_table_id = Column("Genes Table ID", Integer, primary_key=True)
Recommend adding argument autoincrement=True
this ensures that we don't need to populate this column and it manually goes up for each database entry we add.

2024-01-23 13:58 UTC, EKPayne commented on panel.db.2.py
> +            {self.refseq_id} {self.ensembl_select} {self.main_select} {self.main_clinical})"
As per Emma's comment make sure to change main to mane here as well.

2024-01-23 13:58 UTC, EKPayne commented on panel.db.2.py
> +def parse(file):
This wasn't working for me to parse the json file. 

I know we were discussing json.load so I did a little playing around and this seems to work for me:

```
# create an empty database

engine = create_engine("sqlite:///panel_db.db", echo=True)

# create an empty database with the structure outlined above

Base.metadata.create_all(bind=engine)

Session = sessionmaker(bind=engine)
session = Session()

with open ('test_data/123_VV_output.json', 'r') as json_file: # this is the relative path in my directory
    data = json.load(json_file)

print(data)

for item in data:
    new_record = Genes(**item)
    session.add(new_record)

session.commit()
```

NOTE: I have used the relative path for the json file based on how i saved it within my project locally.
I would recommend that you maybe push the test json file to the repository as well and replace the relative path above with one that suits the way you saved it. That when everybody should be able to run the code locally in the same way

2024-01-23 16:34 UTC, EKPayne requested changes

2024-01-23 16:34 UTC, EKPayne commented on panel.db.2.py
> +    panel_id_v = Column(Integer, ForeignKey("panels.Panel ID and Version Number"))
This needs to be a Float data type not int.

2024-01-23 16:34 UTC, EKPayne commented on panel.db.2.py
> +    hgnc_id = Column("HGNC ID", String)
This should be an int

2024-01-23 16:34 UTC, EKPayne commented on panel.db.2.py
> +    omim_no = Column("OMIM", String)
this should be an int

2024-01-23 16:34 UTC, EKPayne commented on panel.db.2.py
> +with open ('/home/stpuser/manchester/Software_assessment/test_output.json', 'r') as json_file:
Recommend updating this to the relative path within the repository 
`"test_output.json"`

The absolute path assumes stpuser which won't.

2024-01-24 09:29 UTC, aoprince commented on panel.db.2.py
> +    omim_no = Column("OMIM", String)
As agreed, not necessary

2024-01-24 10:53 UTC, EKPayne commented
All comments and concerns addressed. Can now be merged into develop.

2024-01-24 10:54 UTC, merged